<form action="songs-save" method="POST" class="my-4">
    <div class="row">
        <div class="form-group">
            <label>Canción</label>
            <input required name="cancion" type="text" placeholder="Ingrese el nombre de la canción" class="form-control">
        </div>
        <div class="form-group">
            <label>Álbum</label>
            <select required name="album" class="form-control">
                <option selected disabled>Seleccione el álbum</option>
                <?php foreach ($albums as $item) : ?>
                    <option value="<?= $item->album_id ?>"><?= $item->album_nombre ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class=row>
        <div class="col-6">
            <label>Duración</label>
            <input required name="duracion" type="number" placeholder="Ingrese duración (en segundos)" class="form-control">
        </div>
    
        <div class="col-6">
            <label>Track</label>
            <input required name="track" type="number" placeholder="Ingrese numero de track" class="form-control">
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>