<form action="add" method="POST" class="my-4">
    <div class="row">
        <div class="form-group">
            <label>Canción</label>
            <input required name="cancion" type="text" class="form-control">
        </div>

        <div class="form-group">
            <label>Album</label>
            <input required name="album" type="text" class="form-control"> 
        </div>
    </div>

    <div class=row>
        <div class="col-6">
            <label>Duración</label>
            <input required name="duracion" type="text" placeholder="Ingrese duración (en segundos)" class="form-control">
        </div>
    
        <div class="col-6">
            <label>Número de Track</label>
            <input required name="track" type="number" class="form-control">
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>