<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>TUDAI - Clasicos 80/90</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="albums">TUDAI - Clasicos 80/90</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="albums">Albumes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="songs">Canciones</a>
                        </li>

                        <?php if ($this->session) : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="login">Login</a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <!-- inicio main container -->
    <main class="container mt-3">