<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<ul class="list-group">
    <?php foreach ($songs as $item) : ?>
        <li class="list-group-item item-task">
            <div>
                <a href="songs/<?= $item->cancion_id?>">
                <b><?= $item->cancion_nombre ?></b>
                </a>
                | <?= $item->album_nombre ?>
                | Duración : <?= $item->duracion ?>
                | Track : <?= $item->track ?>
            </div>
            <?php if ($this->session) : ?>
            <div class="actions">
                <a href="songs-edit/<?= $item->cancion_id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                <a href="songs-remove/<?= $item->cancion_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </div>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ul>

<?php require './app/templates/footer.phtml' ?>