<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<h4 class="ps-2 fw-bold">Álbumes:</h4>
<table class="table">
    <thead>
        <tr>
            <th>Álbum</th>
            <th>Artista</th>
            <th>Año</th>
            <th>Discográfica</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($albums as $item) : ?>
            <tr>
                <th><a href="albums/<?= $item->album_id ?>"><?= $item->album_nombre ?></a></th>
                <td><?= $item->artista ?></td>
                <td><?= $item->anio ?></td>
                <td><?= $item->discografica ?></td>
                <?php if ($this->session) : ?>
                <td>
                    <a href="albums-edit/<?= $item->album_id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                    <a href="albums-remove/<?= $item->album_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>
            </tr>
            <?php endif ?>
            <?php endforeach ?>
        </tbody>
</table>

<?php require './app/templates/footer.phtml' ?>