<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<h4 class="ps-2 fw-bold">Canciones:</h4>
<table class="table">
    <thead>
        <tr>
            <th>Canción</th>
            <th>Álbum</th>
            <th>Duración</th>
            <th>Track</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($songs as $item) : ?>
            <tr>
                <th><a href="songs/<?= $item->cancion_id?>"><?= $item->cancion_nombre ?></a></th>
                <td><a href="albums/<?= $item->album ?>"><?= $item->album_nombre ?></a></td>
                <td><?= $item->duracion ?></td>
                <td><?= $item->track ?></td>
                <?php if ($this->session) : ?>
                <td>
                    <a href="songs-edit/<?= $item->cancion_id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                    <a href="songs-remove/<?= $item->cancion_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>
            </tr>
            <?php endif ?>
            <?php endforeach ?>
        </tbody>
</table>

<?php require './app/templates/footer.phtml' ?>