<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<h4>Albumes:</h4>
<ul class="list-group">
    <?php foreach ($albums as $item) : ?>
        <li class="list-group-item item-task">
            <div>
                <a href="albums/<?= $item->album_id ?>">
                <b><?= $item->album_nombre ?></b>
                </a>
                | <?= $item->artista ?>
                | Año: <?= $item-> anio ?>
                | Discografica: <?= $item->discografica ?> 
            </div>
            <?php if ($this->session) : ?>
            <div class="actions">
                <a href="albums-edit/<?= $item->album_id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                <a href="albums-remove/<?= $item->album_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </div>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ul>

<?php require './app/templates/footer.phtml' ?>