<?php require './app/templates/header.phtml' ?>

<?php if ( AuthHelper::check() ) : ?><h4>La sesion ya fue iniciada <a href="albums" class="link-secondary link-underline link-underline-opacity-0">(volver)</a></h4>
<?php else : ?>
<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="user">Usuario</label>
            <input type="text" required class="form-control" id="user" name="user">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>
<?php endif ?>

<?php require './app/templates/footer.phtml' ?>