<?php require './app/templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <?php if ( AuthHelper::check() ) : ?> <h3>La sesion ya fue iniciada</h3> <?php else : ?>
    <form method="POST" action="users/auth">
        <div class="form-group">
            <label for="user">Usuario</label>
            <input type="text" required class="form-control" id="user" name="user">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
    <?php endif ?>
</div>

<?php require './app/templates/footer.phtml' ?>